import './globals.css'
import type { Metadata } from 'next'
import { Blinker } from 'next/font/google'

const font_google = Blinker({ weight: ['300', '400', '600'], style: ['normal'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font_google.className}>{children}</body>
    </html>
  )
}
